### ISSUE TITLE
Enhancement: Can you provide example environment variables in readme.md?

### ISSUE THREAD

**Issue by rafek1241** [YannickRe/azfunc-managedidentityexamples#1]
Can you provide example environment variables in readme.md?

Example dataverseUrl, example user managed idenity name etc.

**Comment by YannickRe** [comment]
Hi @rafek1241 

Thanks for reaching out! I have added a README with the necessary information hopefully it'll work out for you.

**Comment by rafek1241** [comment]
Hi @YannickRe ,
Thank you, I was trying to use it as you showed in a blog but unfortunately I received 400 status code all the time. I have two user assigned identities, used one of them to make a connection to dataverse API with org unit as scope and it couldn't work. Can you more elaborate what user-assigned managed identity needs to have permissions on dynamics and azure?

**Comment by rafek1241** [comment]
I setup user-assigned managed identity (client, not an app) attached to azure function, pass client Id to use with 'azure.identity' and with '...dynamics.client' and after deployment to azure it couldn't work when I tried to call 'gettoken...'

**Comment by rafek1241** [comment]
I set identity as application user on dynamics side as well

**Comment by YannickRe** [comment]
Can't say much more than what the blog states, unfortunately:

1. Create a user-assigned managed identity
2. Attach the user-assigned managed identity to the Function App
3. Create an application user for the user-assigned managed identity in the correct Dataverse environment (currently only possible in the classic UI)
4. Assign the System Administrator role to the user-assigned managed identity
5. Configure the Azure Function environment variables: **DataverseUrl** and **UserAssignedIdentity**

It should work now.

**Comment by YannickRe** [comment]
@rafek1241 what was the solution?

**Comment by rafek1241** [comment]
@YannickRe I didn't look into that yet but it's not  related to this issue which should be closed. Thank you for your cconcern, though. I give you an update when I will manage to fix that :)

**Comment by rafek1241** [comment]
@YannickRe 
Can you share permissions setup on azure AD for user-assigned managed identity? Maybe there is something that I missed.

**Comment by rafek1241** [comment]
I tried again and nothing changed:
```	
"ManagedIdentityCredential.GetToken" was unable to retrieve an access token. Scopes: "[ https://XXX.api.crm4.dynamics.com ]" ParentRequestId: "" Exception: "Azure.Identity.AuthenticationFailedException (0x80131500): ManagedIdentityCredential authentication failed: Service request failed.
Status: 400 (Bad Request)

Headers:
Date: Thu, 07 Oct 2021 12:44:10 GMT
Content-Length: 133

 ---> Azure.RequestFailedException (0x80131500): Service request failed.
Status: 400 (Bad Request)

Headers:
Date: Thu, 07 Oct 2021 12:44:10 GMT
Content-Length: 133
"```

**Comment by rafek1241** [comment]
I will clone your solution and retry with that to ensure that it is not my fault but some infrastructure one.

**Comment by rafek1241** [comment]
After I used your example it seems to work correctly.

**Comment by rafek1241** [comment]
@YannickRe 
Honestly I don't know why my solution didn't worked. Two main differences that I had:
Logging listener:
```
     using var listener = new AzureEventSourceListener(
                    (log, message) =>
                    {
                        _logger.Write(log.Level.ToSerilogLevel(), log.Message, log.Payload.ToArray());
                        if (log.Message.Contains("error", StringComparison.InvariantCultureIgnoreCase))
                        {
                            _logger.Error("Event data of error log: {@EventData}", log);
                        }
                    },
                    EventLevel.LogAlways
                );
```

Execute async:
```
                var response = await client.ExecuteAsync(new WhoAmIRequest());
````

**Comment by rafek1241** [comment]
@YannickRe 
Okay, a stupid issue on my side. I used settings to assign user-assigned identities:
```
  public class UserSettings
    {
        /// <summary>
        /// user-assigned identity for Function A - DynamicsTestUser1
        /// </summary>
        public string FunctionA { get; private set; }
        
        /// <summary>
        /// user-assigned identity for Function B - DynamicsTestUser2
        /// </summary>
        public string FunctionB { get; private set; }
    }
```
but the function app didn't parse it correctly from the configuration because of a typo within configuration setting names. (single `_` instead of `:` or `__`).

Sorry for taking your time and thank you for your help. I appreciate that!
